name: PRCleanup
on:
  pull_request:
    types: [closed]

jobs:
  deployment:
#   runs-on: ubuntu-18.04
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        # Task remove means to remove the helm release.
        helm: helm3
        task: 'remove'
        release: 'back-${{ github.event.pull_request.number }}'
#       release: 'review-back-${{ github.event.pull_request.number }}'
#       version: latest
        version: '${{ github.sha }}'
        track: 'stable'
        chart: './Chart'
#       chart: './4-Demo-Restructured-Megachart/back'
#       values: |
#         region: 'us-west-2'
#         access_key: '${{ secrets.akey }}'
#         secret_key: '${{ secrets.skey }}'
        namespace: 'default'
#       namespace: 'example-helm'
        token: '${{ github.token }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
